version: "3.9"

x-common-env: &common_env
  DB_HOST: db
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_NAME: ${DB_NAME}
  PYTHONUNBUFFERED: "1"

services:
  db:
    image: mysql:8.0
    container_name: hotel_kong_arthur_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hotel_net

  api_gateway:
    build:
      context: .
      dockerfile: api_gateway/DockerFile
    ports:
      - "5050:5000"
    environment:
      <<: *common_env
      BOOKING_SERVICE_URL: http://booking_service:5001
      DRINKS_SERVICE_URL:  http://drinks_service:5002
      GUEST_SERVICE_URL:   http://guest_service:5003
      ROOM_SERVICE_URL:    http://room_service:5004
    depends_on:
      - db
      - booking_service
      - drinks_service
      - guest_service
      - room_service
    networks:
      - hotel_net

  booking_service:
    build:
      context: .
      dockerfile: booking_service/DockerFile
    ports:
      - "5001:5001"
    environment: *common_env
    depends_on:
      - db
    networks:
      - hotel_net

  drinks_service:
    build:
      context: .
      dockerfile: drinks_service/DockerFile
    ports:
      - "5002:5002"
    environment: *common_env
    depends_on:
      - db
    networks:
      - hotel_net

  guest_service:
    build:
      context: .
      dockerfile: guest_service/DockerFile
    ports:
      - "5003:5003"
    environment: *common_env
    depends_on:
      - db
    networks:
      - hotel_net

  room_service:
    build:
      context: .
      dockerfile: room_service/DockerFile
    ports:
      - "5004:5004"
    environment: *common_env
    depends_on:
      - db
    networks:
      - hotel_net

  streamlit_ui:
    build:
      context: .
      dockerfile: streamlit_ui/DockerFile
    ports:
      - "8520:8520"
    environment:
      GATEWAY_URL: http://api_gateway:5000
    depends_on:
      - api_gateway
    networks:
      - hotel_net

volumes:
  db_data:

networks:
  hotel_net: