FROM python:3.12-slim
WORKDIR /app
COPY api_gateway/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY api_gateway/ /app/
EXPOSE 5000
CMD ["python", "app.py"]